package com.ten.devs.cards.cards.flashcards.domain;

import lombok.Builder;

import java.util.UUID;

/**
 * Domain object representing an AI-generated flashcard suggestion.
 * This is a temporary domain object that represents flashcards generated by AI
 * but not yet accepted by the user.
 *
 * Once accepted, these suggestions are converted to Flashcard entities with source='AI'.
 *
 * The id field is optional:
 * - null when creating new suggestions (before saving to DB)
 * - populated when loading from database
 */
@Builder
public record FlashcardSuggestion(
    UUID id,  // Optional - null for new suggestions, populated when loaded from DB
    UUID sessionId,
    String frontContent,
    String backContent
) {
    public FlashcardSuggestion {
        if (sessionId == null) {
            throw new IllegalArgumentException("Session ID cannot be null");
        }
        if (frontContent == null || frontContent.isBlank()) {
            throw new IllegalArgumentException("Front content cannot be null or empty");
        }
        if (backContent == null || backContent.isBlank()) {
            throw new IllegalArgumentException("Back content cannot be null or empty");
        }
        if (frontContent.length() > 1000) {
            throw new IllegalArgumentException("Front content cannot exceed 1000 characters");
        }
        if (backContent.length() > 1000) {
            throw new IllegalArgumentException("Back content cannot exceed 1000 characters");
        }
    }
}