package com.ten.devs.cards.cards.flashcards.domain;

/**
 * Enum representing the source/origin of a flashcard.
 *
 * Used for analytics to track how flashcards are created:
 * - AI: Generated by AI and accepted without modification
 * - AI_USER: Generated by AI but modified by user before acceptance
 * - USER: Manually created by user from scratch
 *
 * Maps to flashcards.source column (VARCHAR(20) with CHECK constraint).
 */
public enum FlashcardSource {
    /**
     * Flashcard generated by AI and accepted without any modifications.
     */
    AI,

    /**
     * Flashcard generated by AI but content was modified by user before acceptance.
     */
    AI_USER,

    /**
     * Flashcard manually created by user from scratch (not AI-generated).
     */
    USER
}